/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battle.of.hero.View.Panel;

/**
 *
 * @author rakas
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        About = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        Setting = new javax.swing.JButton();
        Deck = new javax.swing.JButton();
        Heropedia = new javax.swing.JButton();
        Shop = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        About.setBackground(new java.awt.Color(153, 0, 0));
        About.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        About.setText("Tentang");
        About.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        Help.setBackground(new java.awt.Color(153, 0, 0));
        Help.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Help.setText("Bantuan");
        Help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HelpMouseExited(evt);
            }
        });
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        Quit.setBackground(new java.awt.Color(153, 0, 0));
        Quit.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Quit.setText("Keluar");
        Quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuitMouseExited(evt);
            }
        });
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        Setting.setBackground(new java.awt.Color(153, 0, 0));
        Setting.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Setting.setText("Pengaturan");
        Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
        });
        Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingActionPerformed(evt);
            }
        });

        Deck.setBackground(new java.awt.Color(153, 0, 0));
        Deck.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Deck.setText("Dek");
        Deck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeckMouseExited(evt);
            }
        });
        Deck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeckActionPerformed(evt);
            }
        });

        Heropedia.setBackground(new java.awt.Color(153, 0, 0));
        Heropedia.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Heropedia.setText("Heropedia");
        Heropedia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Heropedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HeropediaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HeropediaMouseExited(evt);
            }
        });
        Heropedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeropediaActionPerformed(evt);
            }
        });

        Shop.setBackground(new java.awt.Color(153, 0, 0));
        Shop.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Shop.setText("Toko");
        Shop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Shop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShopMouseExited(evt);
            }
        });
        Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopActionPerformed(evt);
            }
        });

        Start.setBackground(new java.awt.Color(153, 0, 0));
        Start.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Start.setText("Main");
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartMouseExited(evt);
            }
        });
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battle/of/hero/image/menu.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1110, 1110, 1110)
                            .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(520, 520, 520)
                            .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(570, 570, 570)
                            .addComponent(Heropedia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(580, 580, 580)
                            .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1130, 1130, 1130)
                            .addComponent(Shop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(580, 580, 580)
                            .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Setting))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(560, 560, 560)
                            .addComponent(Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)
                            .addComponent(Heropedia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(480, 480, 480)
                            .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(560, 560, 560)
                            .addComponent(Shop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(560, 560, 560)
                            .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(570, 570, 570)
                            .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(Deck, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
//        About.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
//        About.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_AboutMouseExited

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
//        ABOUT ABOUT = new ABOUT();
//        ABOUT.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_AboutActionPerformed

    private void HelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseEntered
//        Help.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_HelpMouseEntered

    private void HelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseExited
//        Help.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_HelpMouseExited

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
//        Help Help = new Help();
//        Help.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_HelpActionPerformed

    private void QuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseEntered
//        Quit.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_QuitMouseEntered

    private void QuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseExited
//        Quit.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_QuitMouseExited

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
//        if (JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin ingin keluar?", "Warning", JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
//            System.exit(WIDTH);
//        }
    }//GEN-LAST:event_QuitActionPerformed

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered
//        Setting.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited
//        Setting.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_SettingMouseExited

    private void SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingActionPerformed
//        Setting Setting = new Setting();
//        Setting.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_SettingActionPerformed

    private void DeckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeckMouseEntered
//        Deck.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_DeckMouseEntered

    private void DeckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeckMouseExited
//        Deck.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_DeckMouseExited

    private void DeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeckActionPerformed
//        try {
//            //        Deck Deck = new Deck();
//            //        Deck.setVisible(true);
//            //        this.dispose();
//            cDeck deck = new cDeck();
//            this.dispose();
//        } catch (SQLException ex) {
//            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_DeckActionPerformed

    private void HeropediaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeropediaMouseEntered
//        Heropedia.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_HeropediaMouseEntered

    private void HeropediaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeropediaMouseExited
//        Heropedia.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_HeropediaMouseExited

    private void HeropediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeropediaActionPerformed
//        try {
//            //        Heropedia Heropedia = new Heropedia();
//            //        Heropedia.setVisible(true);
//            cHeroPedia hero = new cHeroPedia();
//        } catch (SQLException ex) {
//            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        this.dispose();
    }//GEN-LAST:event_HeropediaActionPerformed

    private void ShopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopMouseEntered
//        Shop.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_ShopMouseEntered

    private void ShopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopMouseExited
//        Shop.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_ShopMouseExited

    private void ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopActionPerformed
//        try {
//            //        Shop Shop = new Shop();
//            //        Shop.setVisible(true);
//            //        this.dispose();
//            cShop shop = new cShop();
//            this.dispose();
//        } catch (SQLException ex) {
//            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_ShopActionPerformed

    private void StartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseEntered
//        Start.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_StartMouseEntered

    private void StartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseExited
//        Start.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_StartMouseExited

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
//        Play Play = new Play();
//        Play.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_StartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Deck;
    private javax.swing.JButton Help;
    private javax.swing.JButton Heropedia;
    private javax.swing.JButton Quit;
    private javax.swing.JButton Setting;
    private javax.swing.JButton Shop;
    private javax.swing.JButton Start;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
