package battle.of.hero.View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author rakas
 */
public class Over extends javax.swing.JFrame {

    /**
     * Creates new form Over
     */
    public Over(int secor) {
        initComponents();
        Score.setText("" + secor);
        if (secor > 300) {
            Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Lopek Besar.png")));
            Panda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Lopek Besar.png")));
        } else if (secor < 300) {
            Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Nangis Besar.png")));
            Panda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Nangis Besar.png")));
        } else {
            Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Seneng Besar.png")));
            Panda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Seneng Besar.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        Panda = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        Panda1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" KUIS CERDAS MATEMATIKA       V 2.0.0");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setBackground(new java.awt.Color(51, 255, 51));
        start.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        start.setText("MAIN MENU");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 270, -1));

        Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Lopek Besar.png"))); // NOI18N
        Panda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PandaMouseClicked(evt);
            }
        });
        getContentPane().add(Panda, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 410, 472));
        Panda.getAccessibleContext().setAccessibleDescription("");

        Score.setFont(new java.awt.Font("Bell MT", 1, 150)); // NOI18N
        Score.setForeground(new java.awt.Color(247, 224, 23));
        Score.setText("500");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 290, 140));

        Panda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Lopek Besar.png"))); // NOI18N
        Panda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panda1MouseClicked(evt);
            }
        });
        getContentPane().add(Panda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 410, 472));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Over.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PandaMouseClicked
//        Random regen = new Random();
//        int acak = regen.nextInt(12);
//        //        Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Nangis.png")));
//        Panda.setIcon(new javax.swing.ImageIcon(getClass().getResource(panda[acak])));
    }//GEN-LAST:event_PandaMouseClicked

    private void Panda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panda1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Panda1MouseClicked

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        start.setBackground(new java.awt.Color(255, 255, 102));
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        start.setBackground(new java.awt.Color(51, 255, 51));
    }//GEN-LAST:event_startMouseExited

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        MainMenu MainMenu = new MainMenu();
        MainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Over().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Panda;
    private static javax.swing.JLabel Panda1;
    private static javax.swing.JLabel Score;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
