/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rakas
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form Play
     */
    int rgbIn = 16711680, rgbOut = 10027008;

    public Play() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JButton();
        Deck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setBackground(new java.awt.Color(153, 0, 0));
        Start.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Start.setText("Classic");
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartMouseExited(evt);
            }
        });
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        getContentPane().add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 50));

        Deck.setBackground(new java.awt.Color(153, 0, 0));
        Deck.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Deck.setText("Arcade");
        Deck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeckMouseExited(evt);
            }
        });
        Deck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeckActionPerformed(evt);
            }
        });
        getContentPane().add(Deck, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 240, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseEntered
        Start.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_StartMouseEntered

    private void StartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMouseExited
        Start.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_StartMouseExited

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        PlayClassic Classic = new PlayClassic();
        Classic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StartActionPerformed

    private void DeckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeckMouseEntered
        Deck.setBackground(new java.awt.Color(rgbIn));
    }//GEN-LAST:event_DeckMouseEntered

    private void DeckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeckMouseExited
        Deck.setBackground(new java.awt.Color(rgbOut));
    }//GEN-LAST:event_DeckMouseExited

    private void DeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeckActionPerformed
        PlayArcade Arcade = new PlayArcade();
        Arcade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DeckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deck;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
